name: "build-test"
on:
  release:
    types:
      - published

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        yarn
        yarn build
    - name: Push changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git add dist/
        git commit -m "Release {{ github.release.tag_name }}"
        git push
  